default:
  image: shreyasramkumar/harmonizing-mri-scans

stages:          # List of stages for jobs, and their order of execution
  - build

before_script:
  - nvidia-smi
  - docker info

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    # run docker image and mount volume with local data folder
    - docker build 
    - echo "Compiling the code..."
    - echo "Compile complete."

