default:
  image: shreyasramkumar/harmonizing-mri-scans:latest

build-job: 
  tags:
    - "3080"
    - charles
    - docker
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[ci]/
      when: on_success #run on success
    - when: manual 
  script:
    - ls
    # - nvidia-smi
    # - python network_tl.py
  # artifacts:
    # paths:
      # - 

