name: Harmonizing MRI Scans

on:
  push:
    branches:
      - main  

jobs:
  nvidia-check:
    runs-on: self-hosted  # This job will run on a self-hosted runner
    container:
      image: shreyasramkumar/harmonizing-mri-scans:latest
      volumes:
        - /home/ramkumars@acct.upmchs.net/Projects/Harmonizing-MRI-Scans/data:/mri-data:rw
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Navigate to Home
      run: cd

    - name: List Directories
      run: ls
